- example/pubspec.yaml
- lib/typeset.dart
- test/src/typeset_test.dart
> feat: format

- README.md
- example/lib/main.dart
- lib/src/typeset.dart
- test/src/typeset_test.dart
> fix: Better formatting and typo fixes

- LICENSE.md
> feat: Create LICENSE.md

- lib/src/typeset_ext.dart
- lib/typeset.dart
- test/src/typeset_test.dart
**READY**
Closes #6
This PR will add an extension to string and return TypeSet as a Widget. Though not an optimal solution. Will enhance in future.
Implementation for this will be as follows
``` dart
Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
//other widgets
'Hello *World!*'.typeset(),
],
);
```
> feat: TypeSetExtension

- CHANGELOG.md
- README.md
- pubspec.yaml
**READY**
Updating readme and bumping up version to publish on pub.dev
> docs: Readme update

- CHANGELOG.md
- example/ios/Runner.xcodeproj/project.pbxproj
- lib/src/typeset.dart
- lib/src/typeset_ext.dart
- pubspec.yaml
**READY**
Added `textAlign` property for alignment.
> feat: text align property

- CHANGELOG.md
- pubspec.yaml
> feat: version upgrade

- .github/FUNDING.yml
**READY**
Adding Github Sponsorship on repo
> docs: Create FUNDING.yml

- CHANGELOG.md
- example/lib/main.dart
- lib/src/typeset.dart
- pubspec.yaml
**READY**
Wrap asterisk with double percent sign
`%%H**lo W**ld%%`
related to #4 
Needs more work
> feat: Bold asterisk

- CHANGELOG.md
- README.md
- pubspec.yaml
> docs: formatting

- example/lib/main.dart
- lib/src/typeset.dart
- lib/src/typeset_parser.dart
- test/src/typeset_test.dart
**READY**
New properties to typeset:
`linkStyle` 
`monospaceStyle`
`recognizer`
> feat: styling for link, monospace. exposed recognizer

- CHANGELOG.md
- pubspec.yaml
> chore: new version

- pubspec.yaml
> chore: Updated dependencies

- .github/workflows/main.yaml
- CHANGELOG.md
- example/pubspec.yaml
- pubspec.yaml
- test/src/typeset_test.dart
> chore: version update

- example/lib/main.dart
- lib/src/typeset_parser.dart
**READY**
Now we can change **fontSize** dynamically through angular brackets `<>`
**_Example:_** `*Bold Text with 20 font size<20>*`
Output: **Bold Text with 20 font size**
> Feat: Support for font size

- CHANGELOG.md
- lib/src/core/typeset_parser.dart
- lib/src/scribble.dart
- lib/typeset.dart
- pubspec.yaml
> perf: google_fonts dependency

- CHANGELOG.md
- README.md
- example/lib/main.dart
- example/macos/Podfile.lock
- example/macos/Runner.xcodeproj/project.pbxproj
- example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/src/typeset.dart
- lib/src/typeset_ext.dart
- test/src/typeset_widget.dart
> refactor: make TypeSet.inputText a positional argument to match Text semantics

- CHANGELOG.md
- pubspec.yaml
> docs: v2.1.0

- CHANGELOG.md
- example/macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.yaml
**READY**
- mocktail as dev_dependency, to avoid any build errors
> fix: moved mocktail to dev_deps

- CHANGELOG.md
- pubspec.yaml
> chore: version update v2.1.1
